# Generated by Django 6.0.5 on 2026-05-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PCController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='My PC', max_length=100)),
                ('is_permitted', models.BooleanField(default=False)),
                ('last_seen_by_esp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
