# Generated by Django 6.0.5 on 2026-05-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pc_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pccontroller',
            name='last_seen_by_esp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
