# Generated by Django 6.0.5 on 2026-05-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcControl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='controluser',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Designates whether this user has been verified by an admin.'),
        ),
    ]
