# Generated by Django 6.0.5 on 2026-05-21 09:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcControl', '0002_controluser_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceControlState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('should_power_on', models.BooleanField(default=False, help_text='True if the user intends to boot the PC, False otherwise.')),
                ('last_heartbeat', models.DateTimeField(default=django.utils.timezone.now, help_text='The exact time the ESP32 last pinged the REST API.')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_states', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Device Control State',
                'verbose_name_plural': 'Device Control States',
            },
        ),
    ]
